services:
  - type: worker
    name: goat-stock-alert
    env: python
    plan: starter
    region: singapore
    branch: main
    envVars:
      - key: NTFY_CHANNEL
        value: https://ntfy.sh/my-stock-alert
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 main.py
    autoDeploy: true
