services:
  - type: web
    name: goat-stock-alert
    env: python3
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 train_model.py
    region: oregon
    branch: main
    autoDeploy: true
