services:
  - type: worker
    name: goat-train-model
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 train_model.py && sleep infinity
    region: oregon
    branch: main
    autoDeploy: true
